default_platform(:ios)

platform :ios do
  desc "Build the iOS app"
  lane :build do
    match(
      type: "adhoc",
      app_identifier: "com.dxsolo.ultimateTexasHoldemPoc",
      readonly: is_ci,
      git_url: "git@github.com:JamesKPreston/uth_fastlane_match.git"
    )
    build_ios_app(
      scheme: "Runner", # by default Flutter projects scheme is called Runner
      export_method: "ad-hoc",
      team_id: "YOUR_TEAM_ID" # Replace with your Apple Developer Team ID
    )
  end
end 